version: '3.8'

services:
  tsst-server:
    # IMPORTANTE: Reemplaza tossalet por tu nombre de usuario de GitHub real
    # y el nombre del repositorio si es diferente
    image: ghcr.io/tossalet/app-servidor-srt:main
    container_name: tsst_server
    restart: always
    network_mode: "host" # Crucial para el rendimiento de SRT y UDP
    volumes:
      - tsst_data:/usr/src/app/data
      - /media:/media # Permite guardar clips en los USBs montados
    environment:
      - NODE_ENV=production

volumes:
  tsst_data:
